---
meta:
  name:           (( param "Name your pipeline" ))

  concourse_username: (( param "Specify your concourse password" ))
  concourse_password: (( param "Specify your concourse password" ))

  jira_username: (( param "Specify your JIRA password" ))
  jira_password: (( param "Specify your JIRA password" ))

  git:
    private_key:  (( param "Specify git repository private key" ))

resource_types:

- name: pipeline-job-resource-type
  type: docker-image
  source:
    repository: ivanvojinovic/pipeline-job-resource
    tag: latest

resources:

- name: pipeline-job-resource
  type: pipeline-job-resource-type
  source:
    username: (( grab meta.concourse_username ))
    password: (( grab meta.concourse_password ))
    usernamejira: (( grab meta.jira_username ))
    passwordjira: (( grab meta.jira_password ))

- name: test-radiators-git-repo
  type: git
  source:
    uri: ssh://git@stash.zipcar.com:7999/tool/test-radiators.git
    private_key: (( grab meta.git.private_key ))
    branch: master

jobs:
- name: jarvis_api_master_isolation_tests
  plan:
    - get: pipeline-job-resource
    - get: test-radiators-git-repo
    - task: isolation-tests-status
      config:
        platform: linux
        image: docker://docker.zipcar.io/cheetah_ruby#ruby23
        inputs:
        - name: pipeline-job-resource
          path: pipeline_job_resource
        - name: test-radiators-git-repo
          path: test_radiators
        run:
          path: test_radiators/test_pipeline/scripts/isolation-tests-status.sh
