---
meta:
  name:           (( param "Name your pipeline" ))

  concourse_username: (( param "Specify your concourse password" ))
  concourse_password: (( param "Specify your concourse password" ))

  jira_username: (( param "Specify your JIRA password" ))
  jira_password: (( param "Specify your JIRA password" ))

  git:
    private_key:  (( param "Specify git repository private key" ))

resource_types:

- name: pipeline-job-resource-type
  type: docker-image
  source:
    repository: ivanvojinovic/pipeline-job-resource
    tag: latest

resources:

- name: pipeline-job-resource
  type: pipeline-job-resource-type
  source:
    concourse_url: http://192.168.72.209/
    username: (( grab meta.concourse_username ))
    password: (( grab meta.concourse_password ))
    pipeline: jarvis_api
    job: static-analysis-dev-branches

- name: pjr-places-sa-dev
  type: pipeline-job-resource-type
  source:
    concourse_url: http://192.168.72.209/
    username: (( grab meta.concourse_username ))
    password: (( grab meta.concourse_password ))
    pipeline: places
    job: static-analysis-dev-branches

- name: test-radiators-git-repo
  type: git
  source:
    uri: ssh://git@stash.zipcar.com:7999/tool/test-radiators.git
    private_key: (( grab meta.git.private_key ))
    branch: master

jobs:
- name: jarvis_api_sa_dev
  plan:
    - get: pipeline-job-resource
      trigger: true
    - get: test-radiators-git-repo
      trigger: true
    - task: jarvis_api_sa_dev-task
      config:
        platform: linux
        image: docker://docker.zipcar.io/cheetah_ruby#ruby23
        inputs:
        - name: pipeline-job-resource
          path: pipeline_job_resource
        - name: test-radiators-git-repo
          path: test_radiators
        run:
          path: test_radiators/test_pipeline/scripts/status.sh
        params:
          PIPELINE: places
          JOB: static-analysis-dev-branches

- name: places_sa_dev
  plan:
    - get: pjr-places-sa-dev
      trigger: true
    - get: test-radiators-git-repo
      trigger: true
    - task: places_sa_dev-task
      config:
        platform: linux
        image: docker://docker.zipcar.io/cheetah_ruby#ruby23
        inputs:
        - name: pjr-places-sa-dev
          path: pipeline_job_resource
        - name: test-radiators-git-repo
          path: test_radiators
        run:
          path: test_radiators/test_pipeline/scripts/status.sh
        params:
          PIPELINE: places
          JOB: static-analysis-dev-branches
